apiVersion: apps/v1
kind: Deployment
metadata:
  name: fish-api
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: fish-api
  template:
    metadata:
      labels:
        app: fish-api
    spec:
      containers:
        - image: reddog.azurecr.io/chzbrgr71/fish-api:v1.1
          name: fish-api
          ports:
          - containerPort: 3000
            protocol: TCP        
          env:
          - name: REDIS_PASSWORD
            value: 'w@lkingth3d0g'
          - name: REDIS_HOST
            value: 'redis-release-master.redis.svc.cluster.local'
          - name: REDIS_PORT
            value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: fish-api
  labels:
    name: fish-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: fish-api              